name: Build

on:
  push:
    branches: ["main"]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.13.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.2

      - name: Cleaning remote docker image and container
        uses: fifsky/ssh-action@master
        continue-on-error: true
        with:
          command: |
            cd /root/portfolio/
            git pull 
            docker build . -t koders-portfolio
            docker rm $(docker stop $(docker ps -a -q --filter ancestor=${{ secrets.DOCKER_HUB_USERNAME }}/koders-portfolio --format="{{.ID}}"))  && 
            docker rmi koders-portfolio
            docker run -d -p 8080:80 --name koders-portfolio koders-portfolio
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          pass: ${{ secrets.REMOTE_PASSWORD}}
